shallow_clone: true
skip_branch_with_pr: true
test: off
cache:
  - '%GOPATH%\pkg\mod\cache -> go.sum'
  - '%LocalAppData%\go-build'
environment:
  GOPATH: C:\gopath
  PATH: '%PROGRAMFILES(x86)%\WiX Toolset v3.11\bin;%PATH%'
  priv_key:
    secure: L5BSEwg49tmcupeUdj3op8BliIBGZNFGxeZAoSrqimgW/5Ten4KuKtDFD7xf3uxFV6aqZxYiC1GW7yJpjaBlphxYI3dm1rlohddNNj2Dz0B8PUoKvbqRHKEuTBWuY2SHBnc+9qTbxor6KRziotU9/AcUS05DvPGtbRT9vtqHwMhSfXuzOyJQFhChIu+RWfozN86Gbd7UEAKcLm4oAEqZj7tkycvuUdEyUgI6sYfiSlivhmMVxEfCYcfSk3fCzKR2p/aMeLA1W9dW5fAJ4OxYDvsXPR6HkhPuIzle71hgrJTW15Fe0UUjTQ1HyNIjvU0wvmj7wDXINpNIKAKgAonWXADytSHBtIHlXWFe3dCBnglmP8RCTvJnlm1FLmDRCOK95M83oE1yc/1qu+MaG5A4tT5BjqPKWqW5CsdLyT5655ytLZ9qMkVa26WTgGP/bPdXMKGusG1Zg+FLgU/YaWm7T3Zq+YOPyeFyFs4ZoqAZtKfm8HmMjY4CZ8BTBeRJz8JsizZQrAQvi7nLsPMj8m2pXT4OR+wJYGjQ7sCjHAbc6FjsSwWo+jqUBx2ZUhdKPKCEcv9/HhR6zVYM1BhT8Ra7XMbZ/uVlNgIPh1kVRPvYVXGnDIaJN56nSk0n6zh0zZLU4BoMcam/QmAYs6kZagUreL5NmBE0R7ufhkoYgCYUVdt1WGLUkDSOcCLtI0EY1+eK8LNy8cj8rz0oXWJgILBSJdrB+od6Gm5C0ihpUV/KleAMa/Tcx0HGA+1inzNZJWr6ZmL3TZOOCNEdTozXSoyz/rVONCUUpSVEOtq/TERNEYwqzgQ7c2etKMi2a//f5TV7bw8v7nFijUfAcdyHQ7m3iQ0jCfNamRUnbxqPuwSCuII4eltwxYm3m2VbbkqQ+tiRsKgbJxz6JyIJd5ydzgQXvYG6oBFuTb9jj+32hPrkrMcWqLUE00JdRf0EqDITaWbyDJ0V65/Oxb16R7S9wnb+4780KgqWQUDUNoNplig4TtpoydzEmBD69KRhJpd08vEw7h25V7BpNqF7Ai6SglleJLLsNgoXPyy1D0cUPXjfl/wu4+Nd5g8apdTJPQk4StFRDUGYkERhmBYS5qY/m5tDTTiIDFkiU8tPGFY2a0F6qFhaIwldsukSk+Q6adpuW4a427fFL3GQglcEN5cBZYQTp7Ze1lAlLab9y2wY8BwtKgmOogQr+mRMGl5CY9o4P+ytua6K77I0xgboE8TDjmau4XL5rT3LcoWIawxdsi8/Emg2K8ZNsY61i2Vc62bf6rF33nP6+wTXF+5Q1w+jHhQEhyrfCXsilDguCAsfzgkBjgQ8DA/HQxo2eCfpzdCMPC36h+den4jO78JLKcSUecNMBzPCadY4f0Mez4N/87o9w2qEf5oRZbVUkgWX9aNSFJtTO5jlMaIRH0KZzdU3nQJIkAM2IA+IEYs5+tyFKbcYgH+ER0vQk7XJYX4bsxAy5YKOHbibXIqokC77kG2RwE/Bz3E/AEkFyGfvkj1Cbqndif1apmjy8vRcsX4kxdqUmH8f6ARfDwus/RocdaWQUu4mVHi7Ek4qgWgUrw69kklKctBh/QlMMBBhgQnybjHfPd+3mbrsdszRshEWz60Qn5voEhaODJz59Rv0oyBZRQENnT9lNrT70DUbf3WsneW+bXbrQCaSpkpOXun6EUwS+6l75nkdxqvSGnHsW9DqNbYMkEmVHaSnble3MEv6JkuuAod2x0MbayXQH/THdYnooi1mNGR9j+5qVRpWlOacWgTGltbf7+SwkRMZ2ZiIC7g2B6gCLtEJwL6N0Q56toIOOoGpt8JhjbX8pAeEEg8zC2RjLiCRdaH6PTAQP+TjeQCYQrEr5ZiHKqUEpZzqD4IG8K7Ds8A45qtOCQUqQgNCocRUmH1E/7qI9RnMnh8ThuJoXewWcSyt4FT8SFZVvS3v7FJv4ge8vRwrf2d0+Z0Qd3cPvD7ezc0dpgjzX8S+I+RQ50FWGyUZrFPGdoHX2ELInsi/k2OwhU8lzFsIpz6H5ceTA6IiQdx6vvXvlbcjU1p44ZOb7CmNlMBNkLN7HryP1BIS1TJyk6CQ1Sj6EEPzc2sYzViDWTNg6I66kzsduP5khp+qJxhB20QjNl2PT0jOzLecEE9u6vWBwXVDN6bFBUpw+66tftG7kG53PPFWAiS5U60NjkxMBfD087f96F+bEFESMZgBTPc9ekNWGT3jMdZmWiECPHZF6eyCWuU/C8Q8M3xv9pure7WUEYOOr0HuQrd1tM8RD565razOD5ws/Vma7DvlAILUjE+IIsGyArc5GfaJw5Ltxyescvit3IXjDJAEyjKF30ZKQH/58sbJmY/8xNUsYfKq4SSItUvn3k4SupqV
install:
  - ps: |
      if ($env:APPVEYOR_REPO_TAG -match "true" ) {
        $fileContent = "-----BEGIN OPENSSH PRIVATE KEY-----`n"
        $fileContent += $env:priv_key.Replace(' ', "`n")
        $fileContent += "`n-----END OPENSSH PRIVATE KEY-----`n"
        Set-Content $env:userprofile\.ssh\id_rsa $fileContent
        git clone git@github.com:just-install/stable.git 2>$null
        git config --global user.email noreply@appveyor.com
        git config --global user.name AppVeyor
      }
build_script:
  - cmd: go run make.go
artifacts:
  - path: just-install.exe
  - path: just-install.msi
deploy:
  artifact: just-install.exe,just-install.msi
  force_update: true
  provider: GitHub
  auth_token:
    secure: tqgQsXIFAw9puhEL+0L65v4smni7SWhx6SMoDpBRwjxLxUKz9mVF/v61x8IpUkOx
  on:
    APPVEYOR_REPO_TAG: true
